### ISSUE TITLE
TypeError: content is null

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/tocbot#38]
This is appearing in my console on pages that have no matching headers data for TocBot to work with:

> TypeError: content is null (tocbot-init.js:9:24)

**Comment by olafgrabienski** [comment]
Thanks for your report! Can you explain it a bit more what you mean by "matching headers data for TocBot"?

**Comment by laryn** [comment]
I think it happens when there are no matches on a page for the "contentSelector" value.

**Comment by olafgrabienski** [comment]
Thanks @laryn - I was able to reproduce the error by changing the contentSelector value from `.l-content` to `.x-content`. The error in the Chrome console is more verbose but I guess it's the same:

> Uncaught TypeError: Cannot read property 'querySelectorAll' of null at Object.attachTocBot [as attach] (tocbot-init.js:9)

Also, the Tocbot block is empty in this case, it doesn't show a table of contents.

I'm not sure how the issue should be fixed. When the element from the *contentSelector* value doesn't exist on a page, it is expected behavior that the Tocbot block doesn't work. However, this should probably be documented more clearly. And maybe there is also a better way to inform people when the error occurs. Or is it possible to prevent the error in the first place?

To be honest, my coding skills are more than limited, so I could definitely need some help. Which behavior would you expect, @laryn? Or do you even have an idea how to fix the issue?

**Comment by olafgrabienski** [comment]
> When the element from the contentSelector value doesn't exist on a page, it is expected behavior that the Tocbot block doesn't work.

Apart of better documentation and error handling, I see a general challenge in placing multiple Tocbot blocks on different pages of a website: The *contentSelector* value is defined centrally in the settings but different pages might not have a suitable *contentSelector* element in common. Possible solution: set the *contentSelector* value in the Tocbot block settings.

**Comment by laryn** [comment]
Thanks @olafgrabienski! 
The functionality is working as I'd expect -- I'd just expect it to handle the condition without needing to display a warning/error.

**Comment by laryn** [comment]
Does this seem reasonable? It seems to prevent the error message.
https://github.com/backdrop-contrib/tocbot/pull/39

**Comment by olafgrabienski** [comment]
I'll have a look, thank you! (Short of time these days, hopefully soon.)

**Comment by olafgrabienski** [comment]
Looks good to me: I've applied the PR on a test site, and the error is gone. I'm going to merge the PR. Thanks again!

@laryn Are you interested to have a bugfix release soon? Or do you already have other ideas for Tocbot which could be included in a new release?

**Comment by laryn** [comment]
@olafgrabienski I'm testing it out for a small site I'm working on -- this is all I've found so far. Thanks for the module!

**Comment by olafgrabienski** [comment]
@laryn You're welcome! Let me know when the site is ready, I'd love to see Tocbot examples in the wild.

I've just made a new release. When you update, maybe have a look at #37. (After updating to v1.x-1.1.1 I had to clear caches to see the Tocbot configuration page again.)
